mqtt:
  button:
  - unique_id: tapo-cam_up
    name: Tapo Cam - Move up
    command_topic: tapo-cam/move/up
    payload_press: '10'
  - unique_id: tapo-cam_down
    name: Tapo Cam - Move down
    command_topic: tapo-cam/move/down
    payload_press: '10'
  - unique_id: tapo-cam_left
    name: Tapo Cam - Move left
    command_topic: tapo-cam/move/left
    payload_press: '10'
  - unique_id: tapo-cam_right
    name: Tapo Cam - Move right
    command_topic: tapo-cam/move/right
    payload_press: '10'
  switch:
  - unique_id: tapo-cam_privacy_switch
    name: Tapo Cam - Privacy Switch
    state_topic: tapo-cam/privacy
    command_topic: tapo-cam/privacy/set
    payload_on: 'ON'
    payload_off: 'OFF'
    state_on: 'ON'
    state_off: 'OFF'
camera:
- platform: ffmpeg
  name: Tapo-C200
  input: -rtsp_transport tcp -i rtsp://<username>:<password>@<ip>:554/stream1