name: Tapo MQTT Bridge
description: Home Assistant Addon to bridge a tp-link tapo c200 security camera to MQTT
version: 1.0.2
slug: tapo_mqtt_bridge
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_client_id: tapo-cam
  logging: true

schema:
  ip: str
  username: str
  password: str
  mqtt_client_id: str
  logging: bool

hassio_api: true
services: 
  - mqtt:need
