name: Tapo MQTT Bridge
description: Home Assistant Addon to bridge a tp-link tapo c200 security camera to MQTT
version: 1.1.12
slug: tapo_mqtt_bridge
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_client_id: tapo-cam
  logging: false
  refresh_token_polling_interval_minutes: 1

schema:
  ip: str
  username: str
  password: str
  mqtt_client_id: str
  logging: bool
  refresh_token_polling_interval_minutes: int

hassio_api: true
services: 
  - mqtt:need

map:
  - config:rw
